
services:
  
  thesis_caddy:
    container_name: thesis-caddy
    image: caddy:2.10.0-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
   
  thesis_backend:
    container_name: thesis-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        FRONTEND_ENDPOINT: https://thesis.tepohi.no
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/usr/src/app # Sync the backend code
      - ./persistent01:/persistent01  # Mount for file access
    environment:
      # - FRONTEND_ENDPOINT=http://localhost:3000
      - PYTHONPATH=/usr/src/app
      - CELERY_BROKER_URL=redis://thesis_redis:6379/0
    networks:
      - caddy_net
  
  thesis_redis:
    image: redis:7-alpine
    container_name: thesis-redis
    restart: unless-stopped
    networks:
      - caddy_net
  
  thesis_celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: thesis-celery
    command: celery -A worker:celery_app worker --loglevel=info --concurrency=4
    depends_on:
      - thesis_backend
      - thesis_redis
    volumes:
      - ./backend/app:/usr/src/app
      - ./persistent01:/persistent01  # Mount for file access
    environment:
      - CELERY_BROKER_URL=redis://thesis_redis:6379/0
    networks:
      - caddy_net
  
  thesis_frontend:
    container_name: thesis-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_ENDPOINT: https://api.thesis.tepohi.no
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app # Sync the frontend code
    networks:
      - caddy_net
    depends_on:
      - thesis_backend

volumes:
  caddy_data:
  caddy_config:
  
networks:
  caddy_net: