
services:
        
  thesis_docker_backend:
    container_name: thesis-docker-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        FRONTEND_ENDPOINT: https://thesis.tepohi.no
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/usr/src/app # Sync the backend code
      - ./persistent01:/persistent01  # Mount thesis_data for file storage
      - ../thesis_test_folder:/thesis_test_folder
    environment:
      # - FRONTEND_ENDPOINT=http://localhost:3000
      - PYTHONPATH=/usr/src/app
  
  thesis_docker_frontend:
    container_name: thesis-docker-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_ENDPOINT: https://api.thesis.tepohi.no
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app # Sync the frontend code
    depends_on:
      - thesis_docker_backend
